- name: Installation and Configuration
  hosts: wsl_ubuntu
  become: true

  tasks:
    - name: Install Docker
      include_role:
        name: docker

    - name: Install Jenkins
      include_role:
        name: jenkins

    - name: Ensure the Docker group exists
      become: on
      group:
        name: docker
        state: present

    - name: Add Jenkins user to Docker group
      become: on
      user:
        name: jenkins
        group: docker
        append: yes

    - name: Ensure the Jenkins group exists
      become: on
      group:
        name: jenkins
        state: present

    - name: Add Docker user to Jenkins group
      become: on
      user:
        name: docker
        group: jenkins
        append: yes

    - name: Restart Jenkins service
      become: on
      ansible.builtin.service:
        name: jenkins
        state: restarted
      notify: restart Jenkins

    - name: Restart Docker
      become: on
      ansible.builtin.service:
        name: docker
        state: restarted
      notify: restart docker
      
